/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nsJznUzFdgz
 */
import {
  CardDescription,
  CardTitle,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";

export function AsEasyAs() {
  return (
    <section className="py-12 px-4 md:px-6 lg:px-8">
      <div className="mx-auto">
        <h2 className="text-3xl font-bold text-center mb-6">
          Custom dashboards as easy as
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="flex flex-col">
            <CardHeader>
              <CardDescription>Step 1</CardDescription>
              <CardTitle>Use your API key to generate types</CardTitle>
            </CardHeader>
            <CardContent>
              <KeyIcon className="h-12 w-12 mb-4 mx-auto text-gray-900 dark:text-gray-50" />
            </CardContent>
          </Card>
          <Card className="flex flex-col">
            <CardHeader>
              <CardDescription>Step 2</CardDescription>
              <CardTitle>Query your analytics provider</CardTitle>
            </CardHeader>
            <CardContent>
              <DatabaseIcon className="h-12 w-12 mb-4 mx-auto text-gray-900 dark:text-gray-50" />
            </CardContent>
          </Card>
          <Card className="flex flex-col">
            <CardHeader>
              <CardDescription>Step 3</CardDescription>
              <CardTitle>Render using typesafe charts</CardTitle>
            </CardHeader>
            <CardContent>
              <BarChartIcon className="h-12 w-12 mb-4 mx-auto text-gray-900 dark:text-gray-50" />
            </CardContent>
          </Card>
        </div>
        <div className="text-center mt-6">
          <Link
            className={`${buttonVariants({
              variant: "default",
            })} h-14 w-42 text-base`}
            href="/docs"
          >
            Get Started
          </Link>
        </div>
      </div>
    </section>
  );
}

function KeyIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="7.5" cy="15.5" r="5.5" />
      <path d="m21 2-9.6 9.6" />
      <path d="m15.5 7.5 3 3L22 7l-3-3" />
    </svg>
  );
}

function DatabaseIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  );
}

function BarChartIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  );
}
